// Single source of truth for all Nifty 100 constituents.
// Yahoo Finance symbols use the .NS suffix for NSE-listed stocks.

export interface Nifty100Stock {
  symbol: string;   // Yahoo Finance symbol (e.g. "RELIANCE.NS")
  name: string;     // Company display name
  sector: string;
}

export const NIFTY100_STOCKS: Nifty100Stock[] = [
  // ─── Nifty 50 ────────────────────────────────────────────────────────────
  { symbol: "RELIANCE.NS",    name: "Reliance Industries",         sector: "Energy" },
  { symbol: "TCS.NS",         name: "Tata Consultancy Services",   sector: "IT" },
  { symbol: "HDFCBANK.NS",    name: "HDFC Bank",                   sector: "Banking" },
  { symbol: "BHARTIARTL.NS",  name: "Bharti Airtel",               sector: "Telecom" },
  { symbol: "ICICIBANK.NS",   name: "ICICI Bank",                  sector: "Banking" },
  { symbol: "INFY.NS",        name: "Infosys",                     sector: "IT" },
  { symbol: "SBIN.NS",        name: "State Bank of India",         sector: "Banking" },
  { symbol: "HINDUNILVR.NS",  name: "Hindustan Unilever",          sector: "FMCG" },
  { symbol: "ITC.NS",         name: "ITC",                         sector: "FMCG" },
  { symbol: "LICI.NS",        name: "LIC of India",                sector: "Insurance" },
  { symbol: "KOTAKBANK.NS",   name: "Kotak Mahindra Bank",         sector: "Banking" },
  { symbol: "LT.NS",          name: "Larsen & Toubro",             sector: "Infrastructure" },
  { symbol: "HCLTECH.NS",     name: "HCL Technologies",            sector: "IT" },
  { symbol: "BAJFINANCE.NS",  name: "Bajaj Finance",               sector: "Finance" },
  { symbol: "MARUTI.NS",      name: "Maruti Suzuki",               sector: "Auto" },
  { symbol: "AXISBANK.NS",    name: "Axis Bank",                   sector: "Banking" },
  { symbol: "SUNPHARMA.NS",   name: "Sun Pharmaceutical",          sector: "Pharma" },
  { symbol: "ADANIENT.NS",    name: "Adani Enterprises",           sector: "Conglomerate" },
  { symbol: "TITAN.NS",       name: "Titan Company",               sector: "Consumer" },
  { symbol: "WIPRO.NS",       name: "Wipro",                       sector: "IT" },
  { symbol: "NTPC.NS",        name: "NTPC",                        sector: "Energy" },
  { symbol: "ULTRACEMCO.NS",  name: "UltraTech Cement",            sector: "Cement" },
  { symbol: "BAJAJFINSV.NS",  name: "Bajaj Finserv",               sector: "Finance" },
  { symbol: "POWERGRID.NS",   name: "Power Grid Corporation",      sector: "Energy" },
  { symbol: "M&M.NS",         name: "Mahindra & Mahindra",         sector: "Auto" },
  { symbol: "ASIANPAINT.NS",  name: "Asian Paints",                sector: "Consumer" },
  { symbol: "NESTLEIND.NS",   name: "Nestle India",                sector: "FMCG" },
  { symbol: "TATAMOTORS.NS",  name: "Tata Motors",                 sector: "Auto" },
  { symbol: "COALINDIA.NS",   name: "Coal India",                  sector: "Mining" },
  { symbol: "HDFCLIFE.NS",    name: "HDFC Life Insurance",         sector: "Insurance" },
  { symbol: "INDUSINDBK.NS",  name: "IndusInd Bank",               sector: "Banking" },
  { symbol: "TECHM.NS",       name: "Tech Mahindra",               sector: "IT" },
  { symbol: "TATASTEEL.NS",   name: "Tata Steel",                  sector: "Metals" },
  { symbol: "ONGC.NS",        name: "ONGC",                        sector: "Energy" },
  { symbol: "JSWSTEEL.NS",    name: "JSW Steel",                   sector: "Metals" },
  { symbol: "ADANIPORTS.NS",  name: "Adani Ports & SEZ",           sector: "Infrastructure" },
  { symbol: "HINDALCO.NS",    name: "Hindalco Industries",         sector: "Metals" },
  { symbol: "GRASIM.NS",      name: "Grasim Industries",           sector: "Diversified" },
  { symbol: "CIPLA.NS",       name: "Cipla",                       sector: "Pharma" },
  { symbol: "SBILIFE.NS",     name: "SBI Life Insurance",          sector: "Insurance" },
  { symbol: "DRREDDY.NS",     name: "Dr. Reddy's Laboratories",    sector: "Pharma" },
  { symbol: "DIVISLAB.NS",    name: "Divi's Laboratories",         sector: "Pharma" },
  { symbol: "TATACONSUM.NS",  name: "Tata Consumer Products",      sector: "FMCG" },
  { symbol: "BAJAJ-AUTO.NS",  name: "Bajaj Auto",                  sector: "Auto" },
  { symbol: "BRITANNIA.NS",   name: "Britannia Industries",        sector: "FMCG" },
  { symbol: "HEROMOTOCO.NS",  name: "Hero MotoCorp",               sector: "Auto" },
  { symbol: "EICHERMOT.NS",   name: "Eicher Motors",               sector: "Auto" },
  { symbol: "APOLLOHOSP.NS",  name: "Apollo Hospitals",            sector: "Healthcare" },
  { symbol: "BPCL.NS",        name: "Bharat Petroleum",            sector: "Energy" },
  { symbol: "BEL.NS",         name: "Bharat Electronics",          sector: "Defence" },

  // ─── Nifty Next 50 ───────────────────────────────────────────────────────
  { symbol: "SHRIRAMFIN.NS",  name: "Shriram Finance",             sector: "Finance" },
  { symbol: "SIEMENS.NS",     name: "Siemens India",               sector: "Industrials" },
  { symbol: "TRENT.NS",       name: "Trent",                       sector: "Retail" },
  { symbol: "HAVELLS.NS",     name: "Havells India",               sector: "Electricals" },
  { symbol: "ICICIGI.NS",     name: "ICICI Lombard",               sector: "Insurance" },
  { symbol: "ICICIPRULI.NS",  name: "ICICI Prudential Life",       sector: "Insurance" },
  { symbol: "MUTHOOTFIN.NS",  name: "Muthoot Finance",             sector: "Finance" },
  { symbol: "BOSCHLTD.NS",    name: "Bosch India",                 sector: "Auto Ancillary" },
  { symbol: "VEDL.NS",        name: "Vedanta",                     sector: "Metals" },
  { symbol: "GAIL.NS",        name: "GAIL (India)",                sector: "Energy" },
  { symbol: "AMBUJACEM.NS",   name: "Ambuja Cements",              sector: "Cement" },
  { symbol: "BANKBARODA.NS",  name: "Bank of Baroda",              sector: "Banking" },
  { symbol: "CHOLAFIN.NS",    name: "Cholamandalam Finance",       sector: "Finance" },
  { symbol: "DABUR.NS",       name: "Dabur India",                 sector: "FMCG" },
  { symbol: "DMART.NS",       name: "Avenue Supermarts (DMart)",   sector: "Retail" },
  { symbol: "GODREJCP.NS",    name: "Godrej Consumer Products",    sector: "FMCG" },
  { symbol: "HDFCAMC.NS",     name: "HDFC Asset Management",       sector: "Finance" },
  { symbol: "INDIGO.NS",      name: "IndiGo (InterGlobe Aviation)",sector: "Aviation" },
  { symbol: "INDUSTOWER.NS",  name: "Indus Towers",                sector: "Telecom" },
  { symbol: "IRCTC.NS",       name: "IRCTC",                       sector: "Travel" },
  { symbol: "JIOFIN.NS",      name: "Jio Financial Services",      sector: "Finance" },
  { symbol: "LTIM.NS",        name: "LTIMindtree",                 sector: "IT" },
  { symbol: "LUPIN.NS",       name: "Lupin",                       sector: "Pharma" },
  { symbol: "MARICO.NS",      name: "Marico",                      sector: "FMCG" },
  { symbol: "MANKIND.NS",     name: "Mankind Pharma",              sector: "Pharma" },
  { symbol: "NAUKRI.NS",      name: "Info Edge (Naukri)",          sector: "Technology" },
  { symbol: "OBEROIRLTY.NS",  name: "Oberoi Realty",               sector: "Real Estate" },
  { symbol: "PFC.NS",         name: "Power Finance Corporation",   sector: "Finance" },
  { symbol: "PIDILITIND.NS",  name: "Pidilite Industries",         sector: "Chemicals" },
  { symbol: "RECLTD.NS",      name: "REC Limited",                 sector: "Finance" },
  { symbol: "SBICARD.NS",     name: "SBI Cards & Payment",         sector: "Finance" },
  { symbol: "SHREECEM.NS",    name: "Shree Cement",                sector: "Cement" },
  { symbol: "TATAPOWER.NS",   name: "Tata Power",                  sector: "Energy" },
  { symbol: "TORNTPHARM.NS",  name: "Torrent Pharmaceuticals",     sector: "Pharma" },
  { symbol: "TVSMOTOR.NS",    name: "TVS Motor Company",           sector: "Auto" },
  { symbol: "VBL.NS",         name: "Varun Beverages",             sector: "Beverages" },
  { symbol: "ZOMATO.NS",      name: "Zomato",                      sector: "Technology" },
  { symbol: "ZYDUSLIFE.NS",   name: "Zydus Lifesciences",          sector: "Pharma" },
  { symbol: "ABB.NS",         name: "ABB India",                   sector: "Industrials" },
  { symbol: "ACC.NS",         name: "ACC",                         sector: "Cement" },
  { symbol: "ADANIGREEN.NS",  name: "Adani Green Energy",          sector: "Energy" },
  { symbol: "ADANIPOWER.NS",  name: "Adani Power",                 sector: "Energy" },
  { symbol: "NHPC.NS",        name: "NHPC",                        sector: "Energy" },
  { symbol: "NYKAA.NS",       name: "Nykaa (FSN E-Commerce)",      sector: "Retail" },
  { symbol: "CANBK.NS",       name: "Canara Bank",                 sector: "Banking" },
  { symbol: "CGPOWER.NS",     name: "CG Power & Industrial",       sector: "Industrials" },
  { symbol: "JSWENERGY.NS",   name: "JSW Energy",                  sector: "Energy" },
  { symbol: "LODHA.NS",       name: "Macrotech Developers (Lodha)",sector: "Real Estate" },
  { symbol: "MAXHEALTH.NS",   name: "Max Healthcare Institute",    sector: "Healthcare" },
  { symbol: "MOTHERSON.NS",   name: "Samvardhana Motherson",       sector: "Auto Ancillary" },
];

// Bare NSE symbols without the .NS suffix, keyed by Yahoo Finance symbol
export const NIFTY100_SYMBOLS = NIFTY100_STOCKS.map((s) => s.symbol);

// Lookup map: symbol → metadata
export const NIFTY100_MAP = new Map(
  NIFTY100_STOCKS.map((s) => [s.symbol, s])
);
